import {getDb} from "@/lib/cloudflare";
import type {AdvisorSession} from "@/lib/session";
export type ClientSummary={id:string;name:string;abn:string|null;gstMode:string;spend:number;savings:number;subscriptions:number;status:string;progress:number};
export type SubscriptionRow={id:string;clientId:string;clientName:string;provider:string;category:string;billingCycle:string;amount:number;annualCost:number;recordedAnnualCost:number;gstTreatment:string;ownerName:string|null;renewalDate:string|null;noticeDays:number|null;status:string};
export type RecommendationRow={id:string;clientId:string;clientName:string;subscriptionId:string|null;provider:string|null;type:string;title:string;rationale:string;clientWording:string|null;confidence:string;estimatedSaving:number;effort:string;assumptions:string[];evidence:{url:string;title:string;retrievedAt:string;facts:string[]}[];state:string;outcome:string;verifiedSaving:number|null};
const records=(rows:unknown[])=>rows as Record<string,unknown>[];
export async function listClients(session:AdvisorSession):Promise<ClientSummary[]>{const db=await getDb();const result=await db.prepare(`SELECT c.id,c.name,c.abn,c.gst_mode,
 COALESCE((SELECT SUM(CASE WHEN c.gst_mode='EXCLUSIVE' AND s.gst_treatment='GST_INCLUSIVE' THEN ROUND(s.annual_cost_cents/1.1) WHEN c.gst_mode='INCLUSIVE' AND s.gst_treatment='GST_EXCLUSIVE' THEN ROUND(s.annual_cost_cents*1.1) ELSE s.annual_cost_cents END) FROM subscriptions s WHERE s.client_id=c.id AND s.firm_id=c.firm_id AND s.status!='CANCELLED'),0) spend,
 COALESCE((SELECT COUNT(*) FROM subscriptions s WHERE s.client_id=c.id AND s.firm_id=c.firm_id AND s.status!='CANCELLED'),0) subscriptions,
 COALESCE((SELECT SUM(r.estimated_saving_cents) FROM recommendations r WHERE r.client_id=c.id AND r.firm_id=c.firm_id AND r.state IN ('APPROVED','PUBLISHED') AND r.outcome NOT IN ('DISMISSED','VERIFIED')),0) savings,
 COALESCE((SELECT COUNT(*) FROM detection_candidates d WHERE d.client_id=c.id AND d.firm_id=c.firm_id AND d.status='PENDING'),0) pending,
 COALESCE((SELECT COUNT(*) FROM recommendations r WHERE r.client_id=c.id AND r.firm_id=c.firm_id AND r.state='DRAFT'),0) drafts
 FROM clients c WHERE c.firm_id=? ORDER BY c.name`).bind(session.firmId).all();return records(result.results).map(r=>{const pending=Number(r.pending),drafts=Number(r.drafts);return{id:String(r.id),name:String(r.name),abn:r.abn?String(r.abn):null,gstMode:String(r.gst_mode),spend:Number(r.spend)/100,savings:Number(r.savings)/100,subscriptions:Number(r.subscriptions),status:pending?"Detection review":drafts?"Recommendations":Number(r.subscriptions)?"Review ready":"New",progress:pending?45:drafts?70:Number(r.subscriptions)?90:15}})}
export async function getClient(session:AdvisorSession,id:string){return(await listClients(session)).find(c=>c.id===id)??null}
export async function listSubscriptions(session:AdvisorSession,clientId?:string):Promise<SubscriptionRow[]>{const db=await getDb();let sql=`SELECT s.*,c.name client_name,c.gst_mode FROM subscriptions s JOIN clients c ON c.id=s.client_id WHERE s.firm_id=?`;const args:(string|number|null)[]=[session.firmId];if(clientId){sql+=" AND s.client_id=?";args.push(clientId)}sql+=" ORDER BY s.annual_cost_cents DESC";const result=await db.prepare(sql).bind(...args).all();return records(result.results).map(r=>{const recorded=Number(r.annual_cost_cents)/100,gst=String(r.gst_treatment),mode=String(r.gst_mode),presented=mode==="EXCLUSIVE"&&gst==="GST_INCLUSIVE"?recorded/1.1:mode==="INCLUSIVE"&&gst==="GST_EXCLUSIVE"?recorded*1.1:recorded;return{id:String(r.id),clientId:String(r.client_id),clientName:String(r.client_name),provider:String(r.provider),category:String(r.category),billingCycle:String(r.billing_cycle),amount:Number(r.amount_cents)/100,annualCost:Math.round(presented*100)/100,recordedAnnualCost:recorded,gstTreatment:gst,ownerName:r.owner_name?String(r.owner_name):null,renewalDate:r.renewal_date?String(r.renewal_date):null,noticeDays:r.notice_days==null?null:Number(r.notice_days),status:String(r.status)}})}
export async function listRecommendations(session:AdvisorSession,clientId?:string):Promise<RecommendationRow[]>{const db=await getDb();let sql=`SELECT r.*,c.name client_name,s.provider FROM recommendations r JOIN clients c ON c.id=r.client_id LEFT JOIN subscriptions s ON s.id=r.subscription_id WHERE r.firm_id=?`;const args:(string|number|null)[]=[session.firmId];if(clientId){sql+=" AND r.client_id=?";args.push(clientId)}sql+=" ORDER BY CASE r.state WHEN 'DRAFT' THEN 0 WHEN 'APPROVED' THEN 1 ELSE 2 END,r.created_at DESC";const result=await db.prepare(sql).bind(...args).all();return records(result.results).map(r=>({id:String(r.id),clientId:String(r.client_id),clientName:String(r.client_name),subscriptionId:r.subscription_id?String(r.subscription_id):null,provider:r.provider?String(r.provider):null,type:String(r.type),title:String(r.title),rationale:String(r.rationale),clientWording:r.client_wording?String(r.client_wording):null,confidence:String(r.confidence),estimatedSaving:Number(r.estimated_saving_cents)/100,effort:String(r.effort),assumptions:JSON.parse(String(r.assumptions_json)),evidence:JSON.parse(String(r.evidence_json)),state:String(r.state),outcome:String(r.outcome),verifiedSaving:r.verified_saving_cents==null?null:Number(r.verified_saving_cents)/100}))}
export async function listCandidates(session:AdvisorSession,clientId?:string){const db=await getDb();let sql=`SELECT d.*,c.name client_name FROM detection_candidates d JOIN clients c ON c.id=d.client_id WHERE d.firm_id=?`;const args:(string|number|null)[]=[session.firmId];if(clientId){sql+=" AND d.client_id=?";args.push(clientId)}sql+=" ORDER BY d.confidence_score DESC";const result=await db.prepare(sql).bind(...args).all();return records(result.results).map(r=>({id:String(r.id),clientId:String(r.client_id),clientName:String(r.client_name),merchant:String(r.merchant),billingCycle:String(r.billing_cycle),interval:Number(r.median_interval_days),variation:Number(r.amount_variation),score:Number(r.confidence_score),annualCost:Number(r.annual_cost_cents)/100,status:String(r.status),transactionIds:JSON.parse(String(r.transaction_ids_json))as string[]}))}
export async function listImports(session:AdvisorSession){const db=await getDb();const result=await db.prepare(`SELECT i.*,c.name client_name FROM import_batches i JOIN clients c ON c.id=i.client_id WHERE i.firm_id=? ORDER BY i.created_at DESC`).bind(session.firmId).all();return records(result.results)}
export async function listReports(session:AdvisorSession){const db=await getDb();const result=await db.prepare(`SELECT r.*,c.name client_name FROM report_snapshots r JOIN clients c ON c.id=r.client_id WHERE r.firm_id=? ORDER BY r.created_at DESC`).bind(session.firmId).all();return records(result.results)}
export async function listAudit(session:AdvisorSession){const db=await getDb();const result=await db.prepare(`SELECT a.*,c.name client_name,u.email actor_email FROM audit_events a LEFT JOIN clients c ON c.id=a.client_id LEFT JOIN users u ON u.id=a.actor_id WHERE a.firm_id=? ORDER BY a.created_at DESC LIMIT 100`).bind(session.firmId).all();return records(result.results)}
export async function listTransactions(session:AdvisorSession,clientId:string){const db=await getDb();const result=await db.prepare(`SELECT id,description,normalised_merchant,transaction_date,amount_cents,account_name,source FROM transactions WHERE firm_id=? AND client_id=? ORDER BY transaction_date DESC`).bind(session.firmId,clientId).all();return records(result.results)}
export async function audit(session:AdvisorSession,clientId:string|null,action:string,entityType:string,entityId:string|null,summary:Record<string,unknown>){const db=await getDb();await db.prepare(`INSERT INTO audit_events(id,firm_id,client_id,actor_id,action,entity_type,entity_id,summary_json) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),session.firmId,clientId,session.userId,action,entityType,entityId,JSON.stringify(summary)).run()}
