import Link from "next/link";
import {notFound} from "next/navigation";
import {Shell} from "@/components/shell";
import {requireAdvisor} from "@/lib/session";
import {getClient,listCandidates,listRecommendations,listSubscriptions} from "@/lib/repository";
import {confirmCandidate,dismissCandidate,createRecommendation,generateAiRecommendation,updateOutcome} from "@/app/actions";
export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);
export default async function Page({params}:{params:Promise<{id:string}>}){
 const session=await requireAdvisor(),{id}=await params,c=await getClient(session,id);if(!c)notFound();
 const subscriptions=await listSubscriptions(session,id),candidates=await listCandidates(session,id),recommendations=await listRecommendations(session,id);
 return <Shell active="Clients"><div className="page-head"><div><div className="eyebrow">Client workspace</div><h1>{c.name}</h1><p>{c.abn?`ABN ${c.abn} · `:""}{c.gstMode==="INCLUSIVE"?"GST inclusive":"GST exclusive"} view</p></div><div className="actions"><Link className="btn" href={`/imports?client=${id}`}>Import transactions</Link><Link className="btn primary" href={`/reports?client=${id}`}>Build report</Link></div></div>
 <div className="metrics"><M l="Annual spend" v={money(c.spend)}/><M l="Subscriptions" v={String(c.subscriptions)}/><M l="Potential savings" v={money(c.savings)}/><M l="Pending detections" v={String(candidates.filter(x=>x.status==="PENDING").length)}/></div>
 <div className="section-stack"><section className="card"><div className="card-head"><div><div className="card-title">Detection candidates</div><div className="card-sub">Supporting transaction counts and recurrence scores remain visible</div></div></div>{candidates.filter(x=>x.status==="PENDING").length?<table className="table"><thead><tr><th>Merchant</th><th>Cycle</th><th>Annualised</th><th>Confidence</th><th>Decision</th></tr></thead><tbody>{candidates.filter(x=>x.status==="PENDING").map(x=><tr key={x.id}><td><b>{x.merchant}</b><div className="muted">{x.transactionIds.length} transactions · {x.interval} day median</div></td><td>{x.billingCycle}</td><td className="amount">{money(x.annualCost)}</td><td>{Math.round(x.score*100)}%</td><td><div className="actions"><form action={confirmCandidate}><input type="hidden" name="candidateId" value={x.id}/><input type="hidden" name="provider" value={x.merchant}/><button className="btn primary">Confirm</button></form><form action={dismissCandidate}><input type="hidden" name="candidateId" value={x.id}/><button className="btn">Dismiss</button></form></div></td></tr>)}</tbody></table>:<div className="empty-state">No candidates waiting for review.</div>}</section>
 <section className="card"><div className="card-head"><div><div className="card-title">Subscription register</div><div className="card-sub">Confirmed recurring expenditure</div></div><Link className="link" href={`/subscriptions?client=${id}`}>Manage →</Link></div>{subscriptions.length?<table className="table"><thead><tr><th>Provider</th><th>Category</th><th>Annual cost</th><th>Owner</th><th>Renewal</th></tr></thead><tbody>{subscriptions.map(s=><tr key={s.id}><td className="client-name">{s.provider}</td><td>{s.category}</td><td className="amount">{money(s.annualCost)}</td><td>{s.ownerName||"Unassigned"}</td><td>{s.renewalDate||"Not recorded"}</td></tr>)}</tbody></table>:<div className="empty-state">Confirm a detection or add a subscription manually.</div>}</section>
 <section className="card"><div className="card-head"><div><div className="card-title">Recommendations and outcomes</div><div className="card-sub">AI and manual drafts remain internal until advisor approval</div></div></div>{recommendations.map(r=><div className="recommendation" key={r.id}><div><span className={`pill ${r.state==="DRAFT"?"review":""}`}>{r.state}</span><h3>{r.title}</h3><p>{r.rationale}</p><div className="muted">{money(r.estimatedSaving)} potential · {r.confidence} confidence · {r.evidence.length} evidence source(s)</div></div><form action={updateOutcome} className="inline-form"><input type="hidden" name="recommendationId" value={r.id}/><select name="outcome" defaultValue={r.outcome}><option>ESTIMATED</option><option>ACCEPTED</option><option>DISMISSED</option><option>IMPLEMENTED</option><option>VERIFIED</option></select><input name="verifiedSaving" type="number" min="0" step="0.01" placeholder="Verified AUD"/><button className="btn">Save</button></form></div>)}
 {subscriptions.length>0&&<details><summary>Generate evidence-bounded AI draft</summary><form action={generateAiRecommendation} className="form-grid compact"><input type="hidden" name="clientId" value={id}/><label><span>Subscription</span><select name="subscriptionId" required><option value="">Select</option>{subscriptions.map(s=><option key={s.id} value={s.id}>{s.provider}</option>)}</select></label><label><span>Evidence title</span><input name="evidenceTitle" required/></label><label><span>Evidence URL</span><input name="evidenceUrl" type="url" required/></label><label><span>Evidence fact</span><input name="evidenceFact" required/></label><label className="wide"><span>Advisor context</span><textarea name="context"/></label><button className="btn dark">Generate internal draft</button></form></details>}
 <details><summary>Add recommendation manually</summary><form action={createRecommendation} className="form-grid compact"><input type="hidden" name="clientId" value={id}/><label><span>Subscription</span><select name="subscriptionId"><option value="">General review</option>{subscriptions.map(s=><option key={s.id} value={s.id}>{s.provider}</option>)}</select></label><label><span>Type</span><select name="type"><option>CONSOLIDATE</option><option>CANCEL</option><option>DOWNGRADE</option><option>BILLING_CYCLE</option><option>LICENCE_REVIEW</option><option>PRICE_REVIEW</option><option>ALTERNATIVE</option></select></label><label><span>Title</span><input name="title" required/></label><label><span>Potential saving</span><input name="estimatedSaving" type="number" min="0" step="0.01" required/></label><label className="wide"><span>Rationale</span><textarea name="rationale" required/></label><label className="wide"><span>Client wording</span><textarea name="clientWording" required/></label><label><span>Confidence</span><select name="confidence"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label><span>Effort</span><select name="effort"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label><span>Evidence title</span><input name="evidenceTitle" required/></label><label><span>Evidence URL</span><input name="evidenceUrl" type="url" required/></label><label className="wide"><span>Evidence fact</span><input name="evidenceFact" required/></label><label className="wide"><span>Assumption</span><input name="assumption"/></label><button className="btn primary">Save draft</button></form></details></section></div></Shell>
}
function M({l,v}:{l:string;v:string}){return <div className="metric"><div className="metric-label">{l}</div><div className="metric-value">{v}</div></div>}
