import Link from "next/link";
import { Shell } from "@/components/shell";
import { clients, money } from "@/lib/demo-data";

export default function Dashboard(){
  const total=clients.reduce((a,c)=>a+c.spend,0), savings=clients.reduce((a,c)=>a+c.savings,0), subs=clients.reduce((a,c)=>a+c.subscriptions,0);
  return <Shell><div className="page-head"><div><div className="eyebrow">Internal advisor workspace</div><h1>Subscription spend portfolio</h1><p>Monitor client reviews, renewals and savings opportunities.</p></div><div className="actions"><Link className="btn" href="/imports">Import Xero CSV</Link><Link className="btn primary" href="/clients/new">Add client</Link></div></div>
    <div className="metrics"><Metric label="Annual subscription spend" value={money(total)} trend="Across 4 pilot clients"/><Metric label="Savings identified" value={money(savings)} trend="18.4% of reviewed spend"/><Metric label="Active subscriptions" value={String(subs)} trend="12 require attention"/><Metric label="Verified savings" value={money(3560)} trend="6 recommendations implemented"/></div>
    <div className="grid"><div className="section-stack"><section className="card"><div className="card-head"><div><div className="card-title">Portfolio spend trend</div><div className="card-sub">Annualised recurring expenditure · last 8 months</div></div><span className="pill">+4.8% reviewed</span></div><div className="spend-bars">{[48,55,52,64,68,75,79,84].map((h,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:`${h*1.55}px`}}/>{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"][i]}</div>)}</div></section>
      <section className="card"><div className="card-head"><div><div className="card-title">Client reviews</div><div className="card-sub">Pilot portfolio progress</div></div><Link className="link" href="/clients">View all →</Link></div><div className="client-list">{clients.map(c=><Link href={`/clients/${c.id}`} className="client-row" key={c.id}><div><div className="client-name">{c.name}</div><div className="muted">{c.industry}</div></div><div><b>{money(c.spend)}</b><div className="muted">annual spend</div></div><div><b>{money(c.savings)}</b><div className="muted">opportunity</div></div><div><div className="progress"><span style={{width:`${c.progress}%`}}/></div><div className="muted">{c.progress}% complete</div></div><div><span className={`pill ${c.status==="In review"?"review":c.status==="Draft"?"draft":""}`}>{c.status}</span></div></Link>)}</div></section></div>
      <aside className="section-stack"><section className="card"><div className="card-head"><div><div className="card-title">Upcoming renewals</div><div className="card-sub">Next 60 days</div></div><span className="link">12 total</span></div>{[["14","Sep","HubSpot","Harbour Health · $6,720"],["03","Oct","Adobe Creative Cloud","Acme Digital · $1,320"],["18","Oct","Dropbox","Acme Digital · $1,800"]].map(x=><div className="renewal" key={x[2]}><div className="date-box">{x[0]}<small>{x[1]}</small></div><div><h4>{x[2]}</h4><p>{x[3]}</p></div></div>)}</section><section className="card"><div className="card-head"><div><div className="card-title">Review pipeline</div><div className="card-sub">Current work requiring action</div></div></div>{[["Detection candidates","23"],["Draft recommendations","11"],["Awaiting approval","7"],["Client follow-ups","5"]].map(x=><div className="client-row" style={{gridTemplateColumns:"1fr auto"}} key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</section><div className="notice"><b>Advisor control:</b> AI recommendations remain internal until an advisor reviews the evidence and approves publication.</div></aside></div>
  </Shell>
}
function Metric({label,value,trend}:{label:string,value:string,trend:string}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-trend">{trend}</div></div>}
